Hw2
Stalexus/Part-1 pull request #1
Opened 2022-02-18 13:58 UTC by Stalexus

hw2

2022-02-18 17:52 UTC, shuliakleonid requested changes

2022-02-18 17:52 UTC, shuliakleonid commented on css/style.css
> +  font-size: 700 17px 'DM Sans', Arial, sans-serif;position: absolute;
style code

2022-02-18 17:52 UTC, shuliakleonid commented on css/style.css
> +  color: #696871;
I suggest you write body at the top

2022-02-18 17:52 UTC, shuliakleonid commented on index.html
> +                            </div>
Please, before you push the code start a formatting

2022-02-18 17:52 UTC, shuliakleonid commented on index.html
> +                </div>
add alt at img

2022-02-18 18:10 UTC, shuliakleonid commented
## Проверь Свой макет
![image](https://user-images.githubusercontent.com/70269636/154738535-12e34dd1-d734-45b6-ae2b-487e4a1d02a3.png)

2022-02-19 08:29 UTC, Stalexus commented on css/style.css
> +  font-size: 700 17px 'DM Sans', Arial, sans-serif;position: absolute;
changes applied

2022-02-20 11:49 UTC, merged